'''
GUI works just for a Full HD (1920x1080) screen resolution
'''


# This file was generated by the Tkinter Designer
from pathlib import Path

# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Label

#import manual_test as mt
#import automatic_test as at

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\domsp\Desktop\numato_manager\images")

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

class NumatoMgr:
    def __init__(self):
        
        # Main window
        root = Tk()
        root.title("Numato Manager")                                                   # Title
        root.iconbitmap(relative_to_assets("numato_icon.ico"))                         # Main window icon        
        screen_width = 1920
        screen_height = 1080
        root.geometry('{}x{}+{}+{}'.format(screen_width, screen_height, 0, 0))
        root.configure(bg = "#FFFFFF")
                
        # Manual Test Button
        self.manual_button_img = PhotoImage(file=relative_to_assets("manual.png"))
        self.manual_button = Button(image=self.manual_button_img, borderwidth=0, highlightthickness=0, command=lambda: print("manual_button clicked"), relief="flat", background="#FF0000")
        self.manual_button.place(x=0.0, y=0.0, width=screen_width//2, height=screen_height)

        # Automatic Test Button
        self.auto_button_img = PhotoImage(file=relative_to_assets("auto.png"))
        self.auto_button = Button(image=self.auto_button_img, borderwidth=0, highlightthickness=0, command=lambda: print("auto_button clicked"), relief="flat", background="#0000FF")
        self.auto_button.place(x=screen_width//2, y=0.0, width=screen_width//2, height=screen_height)

        self.mainwindow = root

    def run(self):
        #self.canvas.create_text(687.0, 0.0, anchor="nw", text="Numato   Manager", fill="#000000", font=("Inika Bold", 64 * -1))        
        self.mainwindow.mainloop()


if __name__ == "__main__":
    app = NumatoMgr()
    app.run()