# This file was generated by the Tkinter Designer
from pathlib import Path

# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, OptionMenu, Text, Button, Checkbutton, PhotoImage, StringVar, BooleanVar

import utilities as ut

OUTPUT_PATH = Path(__file__).parent

# Laptop
PANEL_PATH = OUTPUT_PATH / Path(r"C:\Users\ITDOSPA\Desktop\NumatoMgr\images\manual\panel")
TEST_PATH = OUTPUT_PATH / Path(r"C:\Users\ITDOSPA\Desktop\NumatoMgr\images\manual\test")

# Desktop
#PANEL_PATH = OUTPUT_PATH / Path(r"C:\Users\domsp\Desktop\numato_manager\images\manual\panel")
#TEST_PATH = OUTPUT_PATH / Path(r"C:\Users\domsp\Desktop\numato_manager\images\manual\test")


class ManualTestPanel:
    def __init__(self, cover_window):        
        self.mainwindow = cover_window

        self.canvas = Canvas(self.mainwindow, bg = "#000000", height = 1017, width = 480, bd = 0, highlightthickness = 0, relief = "ridge")
        self.canvas.place(x=0, y=0)

        # Serial COM Settings Section
        self.canvas.create_text(108.0, 11.0, anchor="nw", text="Serial COM Settings", fill="#FFFFFF", font=("Inter Black", 28 * -1))

        # Select COM Dropdown Menu
        self.com_var = StringVar(self.canvas)
        self.com_var.set("Select COM")
        self.select_com_dropdown_menu = OptionMenu(self.canvas, self.com_var, "      COM1      ", 
                                                                              "      COM2      ", 
                                                                              "      COM3      ", 
                                                                              "      COM4      ", 
                                                                              "      COM14      ", 
                                                                              "      COM255      ")
        self.select_com_dropdown_menu.config(width=12, height=1, anchor='center', font=('Inter', 14))
        self.com_menu = self.select_com_dropdown_menu.nametowidget(self.select_com_dropdown_menu.menuname)
        self.com_menu.configure(font=('Inter', 14))
        self.select_com_dropdown_menu.place(x=152, y=110)
        self.select_com_dropdown_menu.bind("<Configure>", self.on_com_select)

        # Select Baudrate Dropdown Menu
        self.baudrate_var = StringVar(self.canvas)
        self.baudrate_var.set("Select Baudrate")
        self.select_com_dropdown_menu = OptionMenu(self.canvas, self.baudrate_var, "   2400 bps  ", 
                                                                                   "   4800 bps  ", 
                                                                                   "   9600 bps  ", 
                                                                                   "   19200 bps  ", 
                                                                                   "   38400 bps  ", 
                                                                                   "   57600 bps  ", 
                                                                                   "   115200 bps  ",
                                                                                   "   230400 bps  ", 
                                                                                   "   460800 bps  ",
                                                                                   "   500000 bps  ",
                                                                                   "   576000 bps  ",
                                                                                   "   921600 bps  ",
                                                                                   "   1000000 bps  ")

        self.select_com_dropdown_menu.config(width=12, height=1, anchor='center', font=('Inter', 14))
        self.com_menu = self.select_com_dropdown_menu.nametowidget(self.select_com_dropdown_menu.menuname)
        self.com_menu.configure(font=('Inter', 14))
        self.select_com_dropdown_menu.place(x=152, y=210)
        self.select_com_dropdown_menu.bind("<Configure>", self.on_baudrate_select)

        # First Red Line
        self.canvas.create_rectangle(0, 339.0, 480.0, 339.0, fill="#FF0000", outline="")

        # Relays Section
        self.canvas.create_text(196.0, 349.0, anchor="nw", text="Relays", fill="#FFFFFF", font=("Inter Black", 28 * -1))

        self.button_img_relay_1 = PhotoImage(file=self.get_panel_path("relay_1.png"))
        self.button_relay_1 = Button(image=self.button_img_relay_1, borderwidth=0, highlightthickness=0, command=lambda: print("button_relay_1 clicked"), relief="flat")
        self.button_relay_1.place(x=166.0, y=425.0, width=30.0, height=30.0)

        self.button_img_relay_2 = PhotoImage(file=self.get_panel_path("relay_2.png"))
        self.button_relay_2 = Button(image=self.button_img_relay_2, borderwidth=0, highlightthickness=0, command=lambda: print("button_relay_2 clicked"), relief="flat")
        self.button_relay_2.place(x=205.0, y=425.0, width=30.0, height=30.0)

        self.button_img_relay_3 = PhotoImage(file=self.get_panel_path("relay_3.png"))
        self.button_relay_3 = Button(image=self.button_img_relay_3, borderwidth=0, highlightthickness=0, command=lambda: print("button_relay_3 clicked"), relief="flat")
        self.button_relay_3.place(x=245.0, y=425.0, width=30.0, height=30.0)

        self.button_img_relay_4 = PhotoImage(file=self.get_panel_path("relay_4.png"))
        self.button_relay_4 = Button(image=self.button_img_relay_4, borderwidth=0, highlightthickness=0, command=lambda: print("button_relay_4 clicked"), relief="flat")
        self.button_relay_4.place(x=285.0, y=425.0, width=30.0, height=30.0)

        self.button_img_relay_5 = PhotoImage(file=self.get_panel_path("relay_5.png"))
        self.button_relay_5 = Button(image=self.button_img_relay_5, borderwidth=0, highlightthickness=0, command=lambda: print("button_relay_5 clicked"), relief="flat")
        self.button_relay_5.place(x=165.0, y=465.0, width=30.0, height=30.0)

        self.button_img_relay_6 = PhotoImage(file=self.get_panel_path("relay_6.png"))
        self.button_relay_6 = Button(image=self.button_img_relay_6, borderwidth=0, highlightthickness=0, command=lambda: print("button_relay_6 clicked"), relief="flat")
        self.button_relay_6.place(x=205.0, y=465.0, width=30.0, height=30.0)

        self.button_img_relay_7 = PhotoImage(file=self.get_panel_path("relay_7.png"))
        self.button_relay_7 = Button(image=self.button_img_relay_7, borderwidth=0, highlightthickness=0, command=lambda: print("button_relay_7 clicked"), relief="flat")
        self.button_relay_7.place(x=245.0, y=465.0, width=30.0, height=30.0)

        self.button_img_relay_8 = PhotoImage(file=self.get_panel_path("relay_8.png"))
        self.button_relay_8 = Button(image=self.button_img_relay_8, borderwidth=0, highlightthickness=0, command=lambda: print("button_relay_8 clicked"), relief="flat")
        self.button_relay_8.place(x=285.0, y=465.0, width=30.0, height=30.0)

        self.button_img_relay_9 = PhotoImage(file=self.get_panel_path("relay_9.png"))
        self.button_relay_9 = Button(image=self.button_img_relay_9, borderwidth=0, highlightthickness=0, command=lambda: print("button_relay_9 clicked"), relief="flat")
        self.button_relay_9.place(x=165.0, y=505.0, width=30.0, height=30.0)

        self.button_img_relay_10 = PhotoImage(file=self.get_panel_path("relay_10.png"))
        self.button_relay_10 = Button(image=self.button_img_relay_10, borderwidth=0, highlightthickness=0, command=lambda: print("button_relay_10 clicked"), relief="flat")
        self.button_relay_10.place(x=205.0, y=505.0, width=30.0, height=30.0)

        self.button_img_relay_11 = PhotoImage(file=self.get_panel_path("relay_11.png"))
        self.button_relay_11 = Button(image=self.button_img_relay_11, borderwidth=0, highlightthickness=0, command=lambda: print("button_relay_11 clicked"), relief="flat")
        self.button_relay_11.place(x=245.0, y=505.0, width=30.0, height=30.0)

        self.button_img_relay_12 = PhotoImage(file=self.get_panel_path("relay_12.png"))
        self.button_relay_12 = Button(image=self.button_img_relay_12, borderwidth=0, highlightthickness=0, command=lambda: print("button_relay_12 clicked"), relief="flat")
        self.button_relay_12.place(x=285.0, y=505.0, width=30.0, height=30.0)

        self.button_img_relay_13 = PhotoImage(file=self.get_panel_path("relay_13.png"))
        self.button_relay_13 = Button(image=self.button_img_relay_13, borderwidth=0, highlightthickness=0, command=lambda: print("button_relay_13 clicked"), relief="flat")
        self.button_relay_13.place(x=165.0, y=545.0, width=30.0, height=30.0)

        self.button_img_relay_14 = PhotoImage(file=self.get_panel_path("relay_14.png"))
        self.button_relay_14 = Button(image=self.button_img_relay_14, borderwidth=0, highlightthickness=0, command=lambda: print("button_relay_14 clicked"), relief="flat")
        self.button_relay_14.place(x=205.0, y=545.0, width=30.0, height=30.0)

        self.button_img_relay_15 = PhotoImage(file=self.get_panel_path("relay_15.png"))
        self.button_relay_15 = Button(image=self.button_img_relay_15, borderwidth=0, highlightthickness=0, command=lambda: print("button_relay_15 clicked"), relief="flat")
        self.button_relay_15.place(x=245.0, y=545.0, width=30.0, height=30.0)

        self.button_img_relay_16 = PhotoImage(file=self.get_panel_path("relay_16.png"))
        self.button_relay_16 = Button(image=self.button_img_relay_16, borderwidth=0, highlightthickness=0, command=lambda: print("button_relay_16 clicked"), relief="flat")
        self.button_relay_16.place(x=285.0, y=545.0, width=30.0, height=30.0)

        self.canvas.create_text(190.0, 630.0, anchor="nw", text="Select All", fill="#FFFFFF", font=("Inter Medium", 19 * -1))
        self.relays_var = BooleanVar()
        self.button_check_relays = Checkbutton(self.canvas, bg='#000000', variable=self.relays_var, onvalue=True, offvalue=False, command=lambda: print("relay check box clicked"))
        self.button_check_relays.place(x=272, y=629)

        # Second Red Line
        self.canvas.create_rectangle(0, 678.0, 480.0, 678.0, fill="#FF0000", outline="")

        # GPIOs Section
        self.canvas.create_text(199.0, 686.0, anchor="nw", text="GPIOs", fill="#FFFFFF", font=("Inter Black", 28 * -1))

        self.button_img_gpio_0 = PhotoImage(file=self.get_panel_path("gpio_0.png"))
        self.button_gpio_0 = Button(image=self.button_img_gpio_0, borderwidth=0, highlightthickness=0, command=lambda: print("button_gpio_0 clicked"), relief="flat")
        self.button_gpio_0.place(x=147.0, y=824.0, width=36.0, height=36.0)

        self.button_img_gpio_1 = PhotoImage(file=self.get_panel_path("gpio_1.png"))
        self.button_gpio_1 = Button(image=self.button_img_gpio_1, borderwidth=0, highlightthickness=0, command=lambda: print("button_gpio_1 clicked"), relief="flat")
        self.button_gpio_1.place(x=170.0, y=774.0, width=36.0, height=36.0)

        self.button_img_gpio_2 = PhotoImage(file=self.get_panel_path("gpio_2.png"))
        self.button_gpio_2 = Button(image=self.button_img_gpio_2, borderwidth=0, highlightthickness=0, command=lambda: print("button_gpio_2 clicked"), relief="flat")
        self.button_gpio_2.place(x=222.0, y=749.0, width=36.0, height=36.0)

        self.button_img_gpio_3 = PhotoImage(file=self.get_panel_path("gpio_3.png"))
        self.button_gpio_3 = Button(image=self.button_img_gpio_3, borderwidth=0, highlightthickness=0, command=lambda: print("button_gpio_3 clicked"), relief="flat")
        self.button_gpio_3.place(x=271.0, y=774.0, width=36.0, height=36.0)

        self.button_img_gpio_4 = PhotoImage(file=self.get_panel_path("gpio_4.png"))
        self.button_gpio_4 = Button(image=self.button_img_gpio_4, borderwidth=0, highlightthickness=0, command=lambda: print("button_gpio_4 clicked"), relief="flat")
        self.button_gpio_4.place(x=296.0, y=824.0, width=36.0, height=36.0)

        self.button_img_gpio_5 = PhotoImage(file=self.get_panel_path("gpio_5.png"))
        self.button_gpio_5 = Button(image=self.button_img_gpio_5, borderwidth=0, highlightthickness=0, command=lambda: print("button_gpio_5 clicked"), relief="flat")
        self.button_gpio_5.place(x=271.0, y=873.0, width=36.0, height=36.0)

        self.button_img_gpio_6 = PhotoImage(file=self.get_panel_path("gpio_6.png"))
        self.button_gpio_6 = Button(image=self.button_img_gpio_6, borderwidth=0, highlightthickness=0, command=lambda: print("button_gpio_6 clicked"), relief="flat")
        self.button_gpio_6.place(x=222.0, y=899.0, width=36.0, height=36.0)

        self.button_img_gpio_7 = PhotoImage(file=self.get_panel_path("gpio_7.png"))
        self.button_gpio_7 = Button(image=self.button_img_gpio_7, borderwidth=0, highlightthickness=0, command=lambda: print("button_gpio_7 clicked"), relief="flat")
        self.button_gpio_7.place(x=170.0, y=873.0, width=36.0, height=36.0)

        self.canvas.create_text(190.0, 968.0, anchor="nw", text="Select All", fill="#FFFFFF", font=("Inter Medium", 19 * -1))
        self.gpios_var = BooleanVar()
        self.button_check_relays = Checkbutton(self.canvas, bg='#000000', variable=self.gpios_var, onvalue=True, offvalue=False, command=lambda: print("gpio check box clicked"))
        self.button_check_relays.place(x=272, y=967)                    

    def get_panel_path(self, path: str) -> Path:
        return PANEL_PATH / Path(path)

    def on_com_select(self, event):
        selected_value = self.com_var.get()
        print(f"Selected COM: {selected_value}")
        
    def on_baudrate_select(self, event):
        selected_value = self.baudrate_var.get()
        print(f"Selected Baudrate: {selected_value}")
    
    def run(self):
        self.mainwindow.mainloop()


class ManualTestSection:
    def __init__(self, cover_window):        
        self.mainwindow = cover_window

        # Horizontal Shift
        self.shift = 480.0
        
        self.canvas = Canvas(self.mainwindow, bg = "#FF0000", height = 1017, width = 1440, bd = 0, highlightthickness = 0, relief = "ridge")
        self.canvas.place(x=0 + self.shift, y=0)

        # Relays Section
        self.canvas.create_text(365.0, 25.0, anchor="nw", text="1", fill="#FFFFFF", font=("Inter Medium", 24 * -1))
        self.relay_img_1 = PhotoImage(file=self.get_test_path("open.png"))
        self.relay_1 = self.canvas.create_image(372.0, 88.0, image=self.relay_img_1)

        self.canvas.create_text(597.0, 25.0, anchor="nw", text="2", fill="#FFFFFF", font=("Inter Medium", 24 * -1))
        self.relay_img_2 = PhotoImage(file=self.get_test_path("open.png"))
        self.relay_2 = self.canvas.create_image(604.0, 88.0, image=self.relay_img_2)

        self.canvas.create_text(828.0, 25.0, anchor="nw", text="3", fill="#FFFFFF", font=("Inter Medium", 24 * -1))
        self.relay_img_3 = PhotoImage(file=self.get_test_path("open.png"))
        self.relay_3 = self.canvas.create_image(836.0, 88.0, image=self.relay_img_3)

        self.canvas.create_text(1060.0, 25.0, anchor="nw", text="4", fill="#FFFFFF", font=("Inter Medium", 24 * -1))
        self.relay_img_4 = PhotoImage(file=self.get_test_path("open.png"))
        self.relay_4 = self.canvas.create_image(1068.0, 88.0, image=self.relay_img_4)

        self.canvas.create_text(365.0, 148.0, anchor="nw", text="5", fill="#FFFFFF", font=("Inter Medium", 24 * -1))
        self.relay_img_5 = PhotoImage(file=self.get_test_path("open.png"))
        self.relay_5 = self.canvas.create_image(372.0, 211.0, image=self.relay_img_5)

        self.canvas.create_text(597.0, 148.0, anchor="nw", text="6", fill="#FFFFFF", font=("Inter Medium", 24 * -1))
        self.relay_img_6 = PhotoImage(file=self.get_test_path("open.png"))
        self.relay_6 = self.canvas.create_image(604.0, 211.0, image=self.relay_img_6)

        self.canvas.create_text(828.0, 148.0, anchor="nw", text="7", fill="#FFFFFF", font=("Inter Medium", 24 * -1))
        self.relay_img_7 = PhotoImage(file=self.get_test_path("open.png"))
        self.relay_7 = self.canvas.create_image(836.0, 211.0, image=self.relay_img_7)

        self.canvas.create_text(1060.0, 148.0, anchor="nw", text="8", fill="#FFFFFF", font=("Inter Medium", 24 * -1))
        self.relay_img_8 = PhotoImage(file=self.get_test_path("open.png"))
        self.relay_8 = self.canvas.create_image(1068.0, 211.0, image=self.relay_img_8)

        self.canvas.create_text(365.0, 270.0, anchor="nw", text="9", fill="#FFFFFF", font=("Inter Medium", 24 * -1))
        self.relay_img_9 = PhotoImage(file=self.get_test_path("open.png"))
        self.relay_9 = self.canvas.create_image(372.0, 333.0, image=self.relay_img_9)

        self.canvas.create_text(589.0, 270.0, anchor="nw", text="10", fill="#FFFFFF", font=("Inter Medium", 24 * -1))
        self.relay_img_10 = PhotoImage(file=self.get_test_path("open.png"))
        self.relay_10 = self.canvas.create_image(604.0, 333.0, image=self.relay_img_10)

        self.canvas.create_text(820.0, 270.0, anchor="nw", text="11", fill="#FFFFFF", font=("Inter Medium", 24 * -1))
        self.relay_img_11 = PhotoImage(file=self.get_test_path("open.png"))
        self.relay_11 = self.canvas.create_image(836.0, 333.0, image=self.relay_img_11)

        self.canvas.create_text(1051.0, 270.0, anchor="nw", text="12", fill="#FFFFFF", font=("Inter Medium", 24 * -1))
        self.relay_img_12 = PhotoImage(file=self.get_test_path("open.png"))
        self.relay_12 = self.canvas.create_image(1068.0, 333.0, image=self.relay_img_12)

        self.canvas.create_text(357.0, 392.0, anchor="nw", text="13", fill="#FFFFFF", font=("Inter Medium", 24 * -1))
        self.relay_img_13 = PhotoImage(file=self.get_test_path("open.png"))
        self.relay_13 = self.canvas.create_image(372.0, 455.0, image=self.relay_img_13)

        self.canvas.create_text(589.0, 392.0, anchor="nw", text="14", fill="#FFFFFF", font=("Inter Medium", 24 * -1))
        self.relay_img_14 = PhotoImage(file=self.get_test_path("open.png"))
        self.relay_14 = self.canvas.create_image(604.0, 455.0, image=self.relay_img_14)

        self.canvas.create_text(820.0, 392.0, anchor="nw", text="15", fill="#FFFFFF", font=("Inter Medium", 24 * -1))
        self.relay_img_15 = PhotoImage(file=self.get_test_path("open.png"))
        self.relay_15 = self.canvas.create_image(836.0, 455.0, image=self.relay_img_15)

        self.canvas.create_text(1051.0, 392.0, anchor="nw", text="16", fill="#FFFFFF", font=("Inter Medium", 24 * -1))
        self.relay_img_16 = PhotoImage(file=self.get_test_path("open.png"))
        self.relay_16 = self.canvas.create_image(1068.0, 455.0, image=self.relay_img_16)

        # First Line
        self.canvas.create_rectangle(0, 526.0, 1440.0, 526.0, fill="#000000", outline="")

        #GPIOs Section
        self.canvas.create_text(365.0, 568.0, anchor="nw", text="0", fill="#FFFFFF", font=("Inter Medium", 24 * -1))
        self.gpio_img_0 = PhotoImage(file=self.get_test_path("off.png"))
        self.gpio_0 = self.canvas.create_image(372.0, 659.0, image=self.gpio_img_0)

        self.canvas.create_text(597.0, 568.0, anchor="nw", text="1", fill="#FFFFFF", font=("Inter Medium", 24 * -1))
        self.gpio_img_1 = PhotoImage(file=self.get_test_path("off.png"))
        self.gpio_1 = self.canvas.create_image(604.0, 659.0, image=self.gpio_img_1)

        self.canvas.create_text(828.0, 568.0, anchor="nw", text="2", fill="#FFFFFF", font=("Inter Medium", 24 * -1))
        self.gpio_img_2 = PhotoImage(file=self.get_test_path("off.png"))
        self.gpio_2 = self.canvas.create_image(836.0, 659.0, image=self.gpio_img_2)

        self.canvas.create_text(1060.0, 568.0, anchor="nw", text="3", fill="#FFFFFF", font=("Inter Medium", 24 * -1))
        self.gpio_img_3 = PhotoImage(file=self.get_test_path("off.png"))
        self.gpio_3 = self.canvas.create_image(1068.0, 659.0, image=self.gpio_img_3)

        self.canvas.create_text(365.0, 743.0, anchor="nw", text="4", fill="#FFFFFF", font=("Inter Medium", 24 * -1))
        self.gpio_img_4 = PhotoImage(file=self.get_test_path("off.png"))
        self.gpio_4 = self.canvas.create_image(372.0, 835.0, image=self.gpio_img_4)

        self.canvas.create_text(597.0, 743.0, anchor="nw", text="5", fill="#FFFFFF", font=("Inter Medium", 24 * -1))
        self.gpio_img_5 = PhotoImage(file=self.get_test_path("off.png"))
        self.gpio_5 = self.canvas.create_image(604.0, 835.0, image=self.gpio_img_5)

        self.canvas.create_text(828.0, 743.0, anchor="nw", text="6", fill="#FFFFFF", font=("Inter Medium", 24 * -1))
        self.gpio_img_6 = PhotoImage(file=self.get_test_path("off.png"))
        self.gpio_6 = self.canvas.create_image(836.0, 835.0, image=self.gpio_img_6)

        self.canvas.create_text(1060.0, 743.0, anchor="nw", text="7", fill="#FFFFFF", font=("Inter Medium", 24 * -1))
        self.gpio_img_7 = PhotoImage(file=self.get_test_path("off.png"))
        self.gpio_7 = self.canvas.create_image(1068.0, 835.0, image=self.gpio_img_7)

        # Second Line
        self.canvas.create_rectangle(0, 920.0, 1440.0, 920.0, fill="#000000", outline="")

        # Buttons Section
        self.run_img = PhotoImage(file=self.get_test_path("run.png"))
        self.run_button = Button(image=self.run_img, borderwidth=0, highlightthickness=0, command=lambda: print("run button clicked"), relief="flat")
        self.run_button.place(x=450.0 + self.shift, y=944.0, width=161.0, height=50.0)

        self.quit_img = PhotoImage(file=self.get_test_path("quit.png"))
        self.quit_button = Button(image=self.quit_img, borderwidth=0, highlightthickness=0, command=lambda: print("quit button clicked"), relief="flat")
        self.quit_button.place(x=641.0 + self.shift, y=944.0, width=161.0, height=50.0)

        self.back_img = PhotoImage(file=self.get_test_path("back.png"))
        self.back_button = Button(image=self.back_img, borderwidth=0, highlightthickness=0, command=lambda: print("back button clicked"), relief="flat")
        self.back_button.place(x=832.0 + self.shift, y=944.0, width=161.0, height=50.0)
        
    def get_test_path(self, path: str) -> Path:
        return TEST_PATH / Path(path)

    def run(self):
        self.mainwindow.mainloop()

def on_btn_click(cover_window):
    ut.clear_current_window(cover_window)
    panel = ManualTestPanel(cover_window)
    test = ManualTestSection(cover_window)
    panel.run()
    test.run()