# This file was generated by the Tkinter Designer
from pathlib import Path

# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

import utilities as ut

OUTPUT_PATH = Path(__file__).parent
PANEL_PATH = OUTPUT_PATH / Path(r"C:\Users\domsp\Desktop\numato_manager\images\manual\panel")
TEST_PATH = OUTPUT_PATH / Path(r"C:\Users\domsp\Desktop\numato_manager\images\manual\test")

def get_panel_path(path: str) -> Path:
    return PANEL_PATH / Path(path)

def get_test_path(path: str) -> Path:
    return TEST_PATH / Path(path)




def on_btn_click(curr_window, screen):
    ut.clear_current_window(curr_window)
    pass