
# This file was generated by the Tkinter Designer
from pathlib import Path

# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\domsp\Desktop\numato_manager\GUI\Cover\img")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1920x1080")
window.configure(bg = "#FFFFFF")

canvas = Canvas(window, bg="#FFFFFF", height=1080, width=1920, bd=0, highlightthickness=0, relief="ridge")
canvas.place(x = 0, y = 0)

manual_button_img = PhotoImage(file=relative_to_assets("manual.png"))
manual_button = Button(image=manual_button_img, borderwidth=0, highlightthickness=0, command=lambda: print("manual_button clicked"), relief="flat" )
manual_button.place(x=0.0, y=0.0, width=960.0, height=1080.0)

auto_button_img = PhotoImage(file=relative_to_assets("auto.png"))
auto_button = Button(image=auto_button_img, borderwidth=0, highlightthickness=0, command=lambda: print("auto_button clicked"), relief="flat")
auto_button.place(x=960.0, y=0.0, width=960.0, height=1080.0)

canvas.create_text(687.0, 0.0, anchor="nw", text="Numato   Manager", fill="#000000", font=("Inika Bold", 64 * -1) )
window.resizable(False, False)
window.mainloop()
